part of '../main.dart';

const int _introShowcaseIndex = 0;
const int _ipShowcaseIndex = 1;

const CobeOptions _ipPlaceholderOptions = CobeOptions(
  width: 680,
  height: 680,
  phi: 0,
  theta: 0.1,
  dark: 0.02,
  diffuse: 1.16,
  mapSamples: 11000,
  mapBrightness: 6.2,
  mapBaseBrightness: 0.1,
  baseColor: Color(0xFFF3F3F3),
  markerColor: Color(0xFF2E43FF),
  glowColor: Color(0xFFF0F0F0),
  arcColor: Color(0xFF2E43FF),
  markerElevation: 0.02,
);

final List<_Showcase> _showcases = <_Showcase>[
  _Showcase(
    title: 'GLOBE FLUTTER',
    subtitle: 'Intro',
    options: const CobeOptions(
      width: 680,
      height: 680,
      phi: -0.35,
      theta: 0.1,
      dark: 0.02,
      diffuse: 1.1,
      mapSamples: 11000,
      mapBrightness: 5.8,
      mapBaseBrightness: 0.08,
      baseColor: Color(0xFFF3F3F3),
      markerColor: Color(0xFF2E43FF),
      glowColor: Color(0xFFF0F0F0),
      arcColor: Color(0xFF2E43FF),
      markerElevation: 0.02,
    ),
    overlays: <_OverlayCard>[],
  ),
  _Showcase(
    title: 'YOUR LOCATION',
    subtitle: 'Locate',
    options: _ipPlaceholderOptions,
    overlays: <_OverlayCard>[],
  ),
  _Showcase(
    title: 'LIVE BADGE',
    subtitle: 'Live',
    options: const CobeOptions(
      width: 680,
      height: 680,
      phi: -0.35,
      theta: 0.28,
      dark: 0.02,
      diffuse: 1.16,
      mapSamples: 11000,
      mapBrightness: 6.2,
      mapBaseBrightness: 0.1,
      baseColor: Color(0xFFF3F3F3),
      markerColor: Color(0xFFF13D32),
      glowColor: Color(0xFFF0F0F0),
      arcColor: Color(0xFF2E43FF),
      markerElevation: 0.02,
      markers: <CobeMarker>[
        CobeMarker(
          id: 'sf',
          location: CobeLocation(37.7749, -122.4194),
          size: 0.018,
        ),
        CobeMarker(
          id: 'uk',
          location: CobeLocation(51.5072, -0.1276),
          size: 0.016,
        ),
        CobeMarker(
          id: 'lagos',
          location: CobeLocation(6.5244, 3.3792),
          size: 0.016,
        ),
        CobeMarker(
          id: 'india',
          location: CobeLocation(28.6139, 77.2090),
          size: 0.018,
        ),
        CobeMarker(
          id: 'sydney',
          location: CobeLocation(-33.8688, 151.2093),
          size: 0.016,
        ),
      ],
    ),
    overlays: <_OverlayCard>[
      _OverlayCard(
        id: 'sf',
        title: 'LIVE',
        detail: '2,453 watching',
        accent: Color(0xFFF04438),
        layout: _CardLayout(dx: -110, dy: -34),
      ),
      _OverlayCard(
        id: 'uk',
        title: 'LIVE',
        detail: '2,005 watching',
        accent: Color(0xFFF04438),
        layout: _CardLayout(dx: -50, dy: -42),
      ),
      _OverlayCard(
        id: 'india',
        title: 'LIVE',
        detail: '1,575 watching',
        accent: Color(0xFFF04438),
        layout: _CardLayout(dx: 12, dy: -22),
      ),
      _OverlayCard(
        id: 'lagos',
        title: 'LIVE',
        detail: '1,736 watching',
        accent: Color(0xFFF04438),
        layout: _CardLayout(dx: -82, dy: -28),
      ),
      _OverlayCard(
        id: 'sydney',
        title: 'LIVE',
        detail: '4,444 watching',
        accent: Color(0xFFF04438),
        layout: _CardLayout(dx: -24, dy: -26),
      ),
    ],
  ),
  _Showcase(
    title: 'ANALYTICS',
    subtitle: 'Stats',
    options: const CobeOptions(
      width: 680,
      height: 680,
      phi: 0.15,
      theta: 0.18,
      dark: 0.02,
      diffuse: 1.16,
      mapSamples: 11000,
      mapBrightness: 6.2,
      mapBaseBrightness: 0.1,
      baseColor: Color(0xFFF3F3F3),
      markerColor: Color(0xFF59D17C),
      glowColor: Color(0xFFF0F0F0),
      arcColor: Color(0xFF2E43FF),
      markerElevation: 0.02,
      markers: <CobeMarker>[
        CobeMarker(
          id: 'vancouver',
          location: CobeLocation(49.2827, -123.1207),
          size: 0.018,
        ),
        CobeMarker(
          id: 'mexico',
          location: CobeLocation(19.4326, -99.1332),
          size: 0.018,
        ),
        CobeMarker(
          id: 'newyork',
          location: CobeLocation(40.7128, -74.0060),
          size: 0.018,
        ),
      ],
    ),
    overlays: <_OverlayCard>[
      _OverlayCard(
        id: 'vancouver',
        title: '632',
        detail: '↓ 1%',
        accent: Color(0xFF59D17C),
        layout: _CardLayout(dx: -14, dy: -26),
      ),
      _OverlayCard(
        id: 'newyork',
        title: '1,791',
        detail: '↓ 6%',
        accent: Color(0xFF59D17C),
        layout: _CardLayout(dx: -24, dy: -28),
      ),
      _OverlayCard(
        id: 'mexico',
        title: '1232',
        detail: '↓ 20%',
        accent: Color(0xFF59D17C),
        layout: _CardLayout(dx: -18, dy: -18),
      ),
    ],
  ),
  _Showcase(
    title: 'FLIGHT ROUTES',
    subtitle: 'Flights',
    options: const CobeOptions(
      width: 680,
      height: 680,
      phi: -0.4,
      theta: 0.2,
      dark: 0.02,
      diffuse: 1.2,
      mapSamples: 11000,
      mapBrightness: 5.8,
      mapBaseBrightness: 0.08,
      baseColor: Color(0xFFF3F3F3),
      markerColor: Color(0xFF2E43FF),
      glowColor: Color(0xFFF0F0F0),
      arcColor: Color(0xFF2E43FF),
      arcWidth: 0.9,
      arcHeight: 0.42,
      markerElevation: 0.02,
      markers: <CobeMarker>[
        CobeMarker(
          id: 'jfk',
          location: CobeLocation(40.6413, -73.7781),
          size: 0.016,
        ),
        CobeMarker(
          id: 'lhr',
          location: CobeLocation(51.4700, -0.4543),
          size: 0.016,
        ),
        CobeMarker(
          id: 'dxb',
          location: CobeLocation(25.2532, 55.3657),
          size: 0.014,
        ),
        CobeMarker(
          id: 'sin',
          location: CobeLocation(1.3644, 103.9915),
          size: 0.014,
        ),
        CobeMarker(
          id: 'syd',
          location: CobeLocation(-33.9399, 151.1753),
          size: 0.014,
        ),
        CobeMarker(
          id: 'lax',
          location: CobeLocation(33.9425, -118.4081),
          size: 0.014,
        ),
      ],
      arcs: <CobeArc>[
        CobeArc(
          id: 'jfk-lhr',
          from: CobeLocation(40.6413, -73.7781),
          to: CobeLocation(51.4700, -0.4543),
        ),
        CobeArc(
          id: 'lhr-dxb',
          from: CobeLocation(51.4700, -0.4543),
          to: CobeLocation(25.2532, 55.3657),
        ),
        CobeArc(
          id: 'dxb-sin',
          from: CobeLocation(25.2532, 55.3657),
          to: CobeLocation(1.3644, 103.9915),
        ),
        CobeArc(
          id: 'sin-syd',
          from: CobeLocation(1.3644, 103.9915),
          to: CobeLocation(-33.9399, 151.1753),
        ),
        CobeArc(
          id: 'lax-syd',
          from: CobeLocation(33.9425, -118.4081),
          to: CobeLocation(-33.9399, 151.1753),
        ),
      ],
    ),
    overlays: <_OverlayCard>[
      _OverlayCard(
        id: 'jfk-lhr',
        title: '✈',
        detail: 'JFK → LHR  7h 05m',
        accent: Color(0xFF7B9FFF),
        layout: _CardLayout(dx: -60, dy: -26),
        useArc: true,
        emoji: true,
      ),
      _OverlayCard(
        id: 'lhr-dxb',
        title: '✈',
        detail: 'LHR → DXB  6h 45m',
        accent: Color(0xFF7B9FFF),
        layout: _CardLayout(dx: -60, dy: -26),
        useArc: true,
        emoji: true,
      ),
      _OverlayCard(
        id: 'dxb-sin',
        title: '✈',
        detail: 'DXB → SIN  7h 20m',
        accent: Color(0xFF7B9FFF),
        layout: _CardLayout(dx: -60, dy: -26),
        useArc: true,
        emoji: true,
      ),
      _OverlayCard(
        id: 'lax-syd',
        title: '✈',
        detail: 'LAX → SYD  14h 55m',
        accent: Color(0xFF7B9FFF),
        layout: _CardLayout(dx: -70, dy: -26),
        useArc: true,
        emoji: true,
      ),
    ],
  ),
  _Showcase(
    title: 'WEATHER',
    subtitle: 'Weather',
    options: const CobeOptions(
      width: 680,
      height: 680,
      phi: 0.1,
      theta: 0.12,
      dark: 0.02,
      diffuse: 1.1,
      mapSamples: 11000,
      mapBrightness: 5.5,
      mapBaseBrightness: 0.1,
      baseColor: Color(0xFFF5F3EE),
      markerColor: Color(0xFFFFBF00),
      glowColor: Color(0xFFF5F0E8),
      arcColor: Color(0xFF2E43FF),
      markerElevation: 0.02,
      markers: <CobeMarker>[
        CobeMarker(
          id: 'nyc',
          location: CobeLocation(40.7128, -74.0060),
          size: 0.018,
          color: Color(0xFF74AAFF),
        ),
        CobeMarker(
          id: 'london',
          location: CobeLocation(51.5072, -0.1276),
          size: 0.016,
          color: Color(0xFFAAAABB),
        ),
        CobeMarker(
          id: 'tokyo',
          location: CobeLocation(35.6762, 139.6503),
          size: 0.018,
          color: Color(0xFFFF6B9D),
        ),
        CobeMarker(
          id: 'dubai',
          location: CobeLocation(25.2048, 55.2708),
          size: 0.016,
          color: Color(0xFFFF9500),
        ),
        CobeMarker(
          id: 'sao',
          location: CobeLocation(-23.5505, -46.6333),
          size: 0.016,
          color: Color(0xFF7B5BFF),
        ),
        CobeMarker(
          id: 'cape',
          location: CobeLocation(-33.9249, 18.4241),
          size: 0.014,
          color: Color(0xFFFFD700),
        ),
        CobeMarker(
          id: 'mumbai',
          location: CobeLocation(19.0760, 72.8777),
          size: 0.016,
          color: Color(0xFF4DD97C),
        ),
      ],
    ),
    overlays: <_OverlayCard>[
      _OverlayCard(
        id: 'nyc',
        title: '🌧',
        detail: '14°C',
        accent: Color(0xFF74AAFF),
        layout: _CardLayout(dx: -34, dy: -34),
        emoji: true,
      ),
      _OverlayCard(
        id: 'london',
        title: '☁️',
        detail: '9°C',
        accent: Color(0xFFAAAABB),
        layout: _CardLayout(dx: -30, dy: -34),
        emoji: true,
      ),
      _OverlayCard(
        id: 'tokyo',
        title: '🌸',
        detail: '21°C',
        accent: Color(0xFFFF6B9D),
        layout: _CardLayout(dx: -30, dy: -34),
        emoji: true,
      ),
      _OverlayCard(
        id: 'dubai',
        title: '☀️',
        detail: '38°C',
        accent: Color(0xFFFF9500),
        layout: _CardLayout(dx: -28, dy: -34),
        emoji: true,
      ),
      _OverlayCard(
        id: 'sao',
        title: '⛈️',
        detail: '27°C',
        accent: Color(0xFF7B5BFF),
        layout: _CardLayout(dx: -28, dy: -34),
        emoji: true,
      ),
      _OverlayCard(
        id: 'cape',
        title: '🌤️',
        detail: '24°C',
        accent: Color(0xFFFFD700),
        layout: _CardLayout(dx: -28, dy: -34),
        emoji: true,
      ),
      _OverlayCard(
        id: 'mumbai',
        title: '🌦️',
        detail: '29°C',
        accent: Color(0xFF4DD97C),
        layout: _CardLayout(dx: -28, dy: -34),
        emoji: true,
      ),
    ],
  ),
  _Showcase(
    title: 'OUTDOOR SPORTS',
    subtitle: 'Sports',
    options: const CobeOptions(
      width: 680,
      height: 680,
      phi: 0.5,
      theta: 0.1,
      dark: 0.02,
      diffuse: 1.16,
      mapSamples: 11000,
      mapBrightness: 6,
      mapBaseBrightness: 0.1,
      baseColor: Color(0xFFF3F3F3),
      markerColor: Color(0xFF59D17C),
      glowColor: Color(0xFFF0F0F0),
      arcColor: Color(0xFF59D17C),
      markerElevation: 0.02,
      markers: <CobeMarker>[
        CobeMarker(
          id: 'paris',
          location: CobeLocation(48.8566, 2.3522),
          size: 0.018,
          color: Color(0xFF2E43FF),
        ),
        CobeMarker(
          id: 'melbourne',
          location: CobeLocation(-37.8136, 144.9631),
          size: 0.016,
          color: Color(0xFFFF6B35),
        ),
        CobeMarker(
          id: 'rio',
          location: CobeLocation(-22.9068, -43.1729),
          size: 0.018,
          color: Color(0xFF00C896),
        ),
        CobeMarker(
          id: 'london2',
          location: CobeLocation(51.5072, -0.2),
          size: 0.016,
          color: Color(0xFF9B59B6),
        ),
        CobeMarker(
          id: 'bali',
          location: CobeLocation(-8.3405, 115.0920),
          size: 0.016,
          color: Color(0xFF00B4D8),
        ),
        CobeMarker(
          id: 'swiss',
          location: CobeLocation(46.5197, 7.9699),
          size: 0.014,
          color: Color(0xFFE8E8FF),
        ),
      ],
    ),
    overlays: <_OverlayCard>[
      _OverlayCard(
        id: 'paris',
        title: '⚽',
        detail: 'LIGUE 1',
        accent: Color(0xFF2E43FF),
        layout: _CardLayout(dx: -38, dy: -36),
        emoji: true,
      ),
      _OverlayCard(
        id: 'melbourne',
        title: '🎾',
        detail: 'AUS OPEN',
        accent: Color(0xFFFF6B35),
        layout: _CardLayout(dx: -42, dy: -36),
        emoji: true,
      ),
      _OverlayCard(
        id: 'rio',
        title: '🏄',
        detail: 'WSL PRO',
        accent: Color(0xFF00C896),
        layout: _CardLayout(dx: -38, dy: -36),
        emoji: true,
      ),
      _OverlayCard(
        id: 'london2',
        title: '🏇',
        detail: 'ASCOT',
        accent: Color(0xFF9B59B6),
        layout: _CardLayout(dx: -36, dy: -36),
        emoji: true,
      ),
      _OverlayCard(
        id: 'bali',
        title: '🌊',
        detail: 'SURF CUP',
        accent: Color(0xFF00B4D8),
        layout: _CardLayout(dx: -40, dy: -36),
        emoji: true,
      ),
      _OverlayCard(
        id: 'swiss',
        title: '⛷️',
        detail: 'DOWNHILL',
        accent: Color(0xFFCCCCFF),
        layout: _CardLayout(dx: -42, dy: -36),
        emoji: true,
      ),
    ],
  ),
  _Showcase(
    title: 'NIGHT ROUTES',
    subtitle: 'Night',
    darkCards: true,
    options: const CobeOptions(
      width: 680,
      height: 680,
      phi: -0.4,
      theta: 0.2,
      dark: 1,
      diffuse: 0.7,
      mapSamples: 11000,
      mapBrightness: 2.2,
      mapBaseBrightness: 0,
      baseColor: Color(0xFF060B1F),
      markerColor: Color(0xFF5B8DFF),
      glowColor: Color(0xFF030812),
      arcColor: Color(0xFF4B7BFF),
      arcWidth: 1.2,
      arcHeight: 0.45,
      markerElevation: 0.02,
      markers: <CobeMarker>[
        CobeMarker(
          id: 'jfk',
          location: CobeLocation(40.6413, -73.7781),
          size: 0.016,
        ),
        CobeMarker(
          id: 'lhr',
          location: CobeLocation(51.4700, -0.4543),
          size: 0.016,
        ),
        CobeMarker(
          id: 'dxb',
          location: CobeLocation(25.2532, 55.3657),
          size: 0.014,
        ),
        CobeMarker(
          id: 'sin',
          location: CobeLocation(1.3644, 103.9915),
          size: 0.014,
        ),
        CobeMarker(
          id: 'syd',
          location: CobeLocation(-33.9399, 151.1753),
          size: 0.014,
        ),
        CobeMarker(
          id: 'lax',
          location: CobeLocation(33.9425, -118.4081),
          size: 0.014,
        ),
      ],
      arcs: <CobeArc>[
        CobeArc(
          id: 'jfk-lhr',
          from: CobeLocation(40.6413, -73.7781),
          to: CobeLocation(51.4700, -0.4543),
        ),
        CobeArc(
          id: 'lhr-dxb',
          from: CobeLocation(51.4700, -0.4543),
          to: CobeLocation(25.2532, 55.3657),
        ),
        CobeArc(
          id: 'dxb-sin',
          from: CobeLocation(25.2532, 55.3657),
          to: CobeLocation(1.3644, 103.9915),
        ),
        CobeArc(
          id: 'sin-syd',
          from: CobeLocation(1.3644, 103.9915),
          to: CobeLocation(-33.9399, 151.1753),
        ),
        CobeArc(
          id: 'lax-syd',
          from: CobeLocation(33.9425, -118.4081),
          to: CobeLocation(-33.9399, 151.1753),
        ),
      ],
    ),
    overlays: <_OverlayCard>[
      _OverlayCard(
        id: 'jfk-lhr',
        title: '✈',
        detail: 'JFK → LHR  7h 05m',
        accent: Color(0xFF7B9FFF),
        layout: _CardLayout(dx: -60, dy: -26),
        useArc: true,
        emoji: true,
      ),
      _OverlayCard(
        id: 'lhr-dxb',
        title: '✈',
        detail: 'LHR → DXB  6h 45m',
        accent: Color(0xFF7B9FFF),
        layout: _CardLayout(dx: -60, dy: -26),
        useArc: true,
        emoji: true,
      ),
      _OverlayCard(
        id: 'dxb-sin',
        title: '✈',
        detail: 'DXB → SIN  7h 20m',
        accent: Color(0xFF7B9FFF),
        layout: _CardLayout(dx: -60, dy: -26),
        useArc: true,
        emoji: true,
      ),
      _OverlayCard(
        id: 'lax-syd',
        title: '✈',
        detail: 'LAX → SYD  14h 55m',
        accent: Color(0xFF7B9FFF),
        layout: _CardLayout(dx: -70, dy: -26),
        useArc: true,
        emoji: true,
      ),
    ],
  ),
  _Showcase(
    title: 'DARK PULSE',
    subtitle: 'Pulse',
    darkCards: true,
    options: const CobeOptions(
      width: 680,
      height: 680,
      phi: -0.35,
      theta: 0.28,
      dark: 1,
      diffuse: 0.8,
      mapSamples: 11000,
      mapBrightness: 2,
      mapBaseBrightness: 0,
      baseColor: Color(0xFF060B1F),
      markerColor: Color(0xFFFF4B4B),
      glowColor: Color(0xFF030812),
      arcColor: Color(0xFFFF4B4B),
      markerElevation: 0.02,
      markers: <CobeMarker>[
        CobeMarker(
          id: 'sf',
          location: CobeLocation(37.7749, -122.4194),
          size: 0.018,
        ),
        CobeMarker(
          id: 'uk',
          location: CobeLocation(51.5072, -0.1276),
          size: 0.016,
        ),
        CobeMarker(
          id: 'lagos',
          location: CobeLocation(6.5244, 3.3792),
          size: 0.016,
        ),
        CobeMarker(
          id: 'india',
          location: CobeLocation(28.6139, 77.2090),
          size: 0.018,
        ),
        CobeMarker(
          id: 'sydney',
          location: CobeLocation(-33.8688, 151.2093),
          size: 0.016,
        ),
      ],
    ),
    overlays: <_OverlayCard>[
      _OverlayCard(
        id: 'sf',
        title: 'LIVE',
        detail: '2,453 watching',
        accent: Color(0xFFFF6B6B),
        layout: _CardLayout(dx: -110, dy: -34),
      ),
      _OverlayCard(
        id: 'uk',
        title: 'LIVE',
        detail: '2,005 watching',
        accent: Color(0xFFFF6B6B),
        layout: _CardLayout(dx: -50, dy: -42),
      ),
      _OverlayCard(
        id: 'india',
        title: 'LIVE',
        detail: '1,575 watching',
        accent: Color(0xFFFF6B6B),
        layout: _CardLayout(dx: 12, dy: -22),
      ),
      _OverlayCard(
        id: 'lagos',
        title: 'LIVE',
        detail: '1,736 watching',
        accent: Color(0xFFFF6B6B),
        layout: _CardLayout(dx: -82, dy: -28),
      ),
      _OverlayCard(
        id: 'sydney',
        title: 'LIVE',
        detail: '4,444 watching',
        accent: Color(0xFFFF6B6B),
        layout: _CardLayout(dx: -24, dy: -26),
      ),
    ],
  ),
];
